// flow-typed signature: 8ce34497c1f042347933f0acd1eb451b
// flow-typed version: <<STUB>>/flowgen_v1.2.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flowgen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flowgen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flowgen/lib/__tests__/union_strings.spec' {
  declare module.exports: any;
}

declare module 'flowgen/lib/cli/__tests__/compiler.spec' {
  declare module.exports: any;
}

declare module 'flowgen/lib/cli/__tests__/fixtures.spec' {
  declare module.exports: any;
}

declare module 'flowgen/lib/cli/beautifier' {
  declare module.exports: any;
}

declare module 'flowgen/lib/cli/compiler' {
  declare module.exports: any;
}

declare module 'flowgen/lib/cli/default-exporter' {
  declare module.exports: any;
}

declare module 'flowgen/lib/cli/flow-typed-exporter' {
  declare module.exports: any;
}

declare module 'flowgen/lib/cli/index' {
  declare module.exports: any;
}

declare module 'flowgen/lib/cli/meta' {
  declare module.exports: any;
}

declare module 'flowgen/lib/cli/runner' {
  declare module.exports: any;
}

declare module 'flowgen/lib/index' {
  declare module.exports: any;
}

declare module 'flowgen/lib/namespaceManager' {
  declare module.exports: any;
}

declare module 'flowgen/lib/nodename' {
  declare module.exports: any;
}

declare module 'flowgen/lib/nodes/export' {
  declare module.exports: any;
}

declare module 'flowgen/lib/nodes/factory' {
  declare module.exports: any;
}

declare module 'flowgen/lib/nodes/import' {
  declare module.exports: any;
}

declare module 'flowgen/lib/nodes/module' {
  declare module.exports: any;
}

declare module 'flowgen/lib/nodes/namespace' {
  declare module.exports: any;
}

declare module 'flowgen/lib/nodes/node' {
  declare module.exports: any;
}

declare module 'flowgen/lib/nodes/property' {
  declare module.exports: any;
}

declare module 'flowgen/lib/nodes/variable' {
  declare module.exports: any;
}

declare module 'flowgen/lib/parse' {
  declare module.exports: any;
}

declare module 'flowgen/lib/printers/basics' {
  declare module.exports: any;
}

declare module 'flowgen/lib/printers/common' {
  declare module.exports: any;
}

declare module 'flowgen/lib/printers/declarations' {
  declare module.exports: any;
}

declare module 'flowgen/lib/printers/function' {
  declare module.exports: any;
}

declare module 'flowgen/lib/printers/index' {
  declare module.exports: any;
}

declare module 'flowgen/lib/printers/node' {
  declare module.exports: any;
}

declare module 'flowgen/lib/printers/relationships' {
  declare module.exports: any;
}

declare module 'flowgen/lib/printers/unionNode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flowgen/lib/__tests__/union_strings.spec.js' {
  declare module.exports: $Exports<'flowgen/lib/__tests__/union_strings.spec'>;
}
declare module 'flowgen/lib/cli/__tests__/compiler.spec.js' {
  declare module.exports: $Exports<'flowgen/lib/cli/__tests__/compiler.spec'>;
}
declare module 'flowgen/lib/cli/__tests__/fixtures.spec.js' {
  declare module.exports: $Exports<'flowgen/lib/cli/__tests__/fixtures.spec'>;
}
declare module 'flowgen/lib/cli/beautifier.js' {
  declare module.exports: $Exports<'flowgen/lib/cli/beautifier'>;
}
declare module 'flowgen/lib/cli/compiler.js' {
  declare module.exports: $Exports<'flowgen/lib/cli/compiler'>;
}
declare module 'flowgen/lib/cli/default-exporter.js' {
  declare module.exports: $Exports<'flowgen/lib/cli/default-exporter'>;
}
declare module 'flowgen/lib/cli/flow-typed-exporter.js' {
  declare module.exports: $Exports<'flowgen/lib/cli/flow-typed-exporter'>;
}
declare module 'flowgen/lib/cli/index.js' {
  declare module.exports: $Exports<'flowgen/lib/cli/index'>;
}
declare module 'flowgen/lib/cli/meta.js' {
  declare module.exports: $Exports<'flowgen/lib/cli/meta'>;
}
declare module 'flowgen/lib/cli/runner.js' {
  declare module.exports: $Exports<'flowgen/lib/cli/runner'>;
}
declare module 'flowgen/lib/index.js' {
  declare module.exports: $Exports<'flowgen/lib/index'>;
}
declare module 'flowgen/lib/namespaceManager.js' {
  declare module.exports: $Exports<'flowgen/lib/namespaceManager'>;
}
declare module 'flowgen/lib/nodename.js' {
  declare module.exports: $Exports<'flowgen/lib/nodename'>;
}
declare module 'flowgen/lib/nodes/export.js' {
  declare module.exports: $Exports<'flowgen/lib/nodes/export'>;
}
declare module 'flowgen/lib/nodes/factory.js' {
  declare module.exports: $Exports<'flowgen/lib/nodes/factory'>;
}
declare module 'flowgen/lib/nodes/import.js' {
  declare module.exports: $Exports<'flowgen/lib/nodes/import'>;
}
declare module 'flowgen/lib/nodes/module.js' {
  declare module.exports: $Exports<'flowgen/lib/nodes/module'>;
}
declare module 'flowgen/lib/nodes/namespace.js' {
  declare module.exports: $Exports<'flowgen/lib/nodes/namespace'>;
}
declare module 'flowgen/lib/nodes/node.js' {
  declare module.exports: $Exports<'flowgen/lib/nodes/node'>;
}
declare module 'flowgen/lib/nodes/property.js' {
  declare module.exports: $Exports<'flowgen/lib/nodes/property'>;
}
declare module 'flowgen/lib/nodes/variable.js' {
  declare module.exports: $Exports<'flowgen/lib/nodes/variable'>;
}
declare module 'flowgen/lib/parse.js' {
  declare module.exports: $Exports<'flowgen/lib/parse'>;
}
declare module 'flowgen/lib/printers/basics.js' {
  declare module.exports: $Exports<'flowgen/lib/printers/basics'>;
}
declare module 'flowgen/lib/printers/common.js' {
  declare module.exports: $Exports<'flowgen/lib/printers/common'>;
}
declare module 'flowgen/lib/printers/declarations.js' {
  declare module.exports: $Exports<'flowgen/lib/printers/declarations'>;
}
declare module 'flowgen/lib/printers/function.js' {
  declare module.exports: $Exports<'flowgen/lib/printers/function'>;
}
declare module 'flowgen/lib/printers/index.js' {
  declare module.exports: $Exports<'flowgen/lib/printers/index'>;
}
declare module 'flowgen/lib/printers/node.js' {
  declare module.exports: $Exports<'flowgen/lib/printers/node'>;
}
declare module 'flowgen/lib/printers/relationships.js' {
  declare module.exports: $Exports<'flowgen/lib/printers/relationships'>;
}
declare module 'flowgen/lib/printers/unionNode.js' {
  declare module.exports: $Exports<'flowgen/lib/printers/unionNode'>;
}
