// flow-typed signature: 70d36318cd88a2c4cb0bb60834eae135
// flow-typed version: <<STUB>>/vscode-languageserver-types_v3.7.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-languageserver-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-languageserver-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-languageserver-types/lib/esm/main' {
  declare module.exports: any;
}

declare module 'vscode-languageserver-types/lib/umd/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-languageserver-types/lib/esm/main.js' {
  declare module.exports: $Exports<'vscode-languageserver-types/lib/esm/main'>;
}
declare module 'vscode-languageserver-types/lib/umd/main.js' {
  declare module.exports: $Exports<'vscode-languageserver-types/lib/umd/main'>;
}
