// flow-typed signature: 5320a87229ecc8f48d772fe33f727e58
// flow-typed version: <<STUB>>/vscode-languageserver-protocol_v3.7.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-languageserver-protocol'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-languageserver-protocol' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-languageserver-protocol/lib/main' {
  declare module.exports: any;
}

declare module 'vscode-languageserver-protocol/lib/protocol.colorProvider' {
  declare module.exports: any;
}

declare module 'vscode-languageserver-protocol/lib/protocol.colorProvider.proposed' {
  declare module.exports: any;
}

declare module 'vscode-languageserver-protocol/lib/protocol.configuration' {
  declare module.exports: any;
}

declare module 'vscode-languageserver-protocol/lib/protocol.configuration.proposed' {
  declare module.exports: any;
}

declare module 'vscode-languageserver-protocol/lib/protocol.implementation' {
  declare module.exports: any;
}

declare module 'vscode-languageserver-protocol/lib/protocol' {
  declare module.exports: any;
}

declare module 'vscode-languageserver-protocol/lib/protocol.typeDefinition' {
  declare module.exports: any;
}

declare module 'vscode-languageserver-protocol/lib/protocol.workspaceFolders' {
  declare module.exports: any;
}

declare module 'vscode-languageserver-protocol/lib/protocol.workspaceFolders.proposed' {
  declare module.exports: any;
}

declare module 'vscode-languageserver-protocol/lib/utils/is' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-languageserver-protocol/lib/main.js' {
  declare module.exports: $Exports<'vscode-languageserver-protocol/lib/main'>;
}
declare module 'vscode-languageserver-protocol/lib/protocol.colorProvider.js' {
  declare module.exports: $Exports<'vscode-languageserver-protocol/lib/protocol.colorProvider'>;
}
declare module 'vscode-languageserver-protocol/lib/protocol.colorProvider.proposed.js' {
  declare module.exports: $Exports<'vscode-languageserver-protocol/lib/protocol.colorProvider.proposed'>;
}
declare module 'vscode-languageserver-protocol/lib/protocol.configuration.js' {
  declare module.exports: $Exports<'vscode-languageserver-protocol/lib/protocol.configuration'>;
}
declare module 'vscode-languageserver-protocol/lib/protocol.configuration.proposed.js' {
  declare module.exports: $Exports<'vscode-languageserver-protocol/lib/protocol.configuration.proposed'>;
}
declare module 'vscode-languageserver-protocol/lib/protocol.implementation.js' {
  declare module.exports: $Exports<'vscode-languageserver-protocol/lib/protocol.implementation'>;
}
declare module 'vscode-languageserver-protocol/lib/protocol.js' {
  declare module.exports: $Exports<'vscode-languageserver-protocol/lib/protocol'>;
}
declare module 'vscode-languageserver-protocol/lib/protocol.typeDefinition.js' {
  declare module.exports: $Exports<'vscode-languageserver-protocol/lib/protocol.typeDefinition'>;
}
declare module 'vscode-languageserver-protocol/lib/protocol.workspaceFolders.js' {
  declare module.exports: $Exports<'vscode-languageserver-protocol/lib/protocol.workspaceFolders'>;
}
declare module 'vscode-languageserver-protocol/lib/protocol.workspaceFolders.proposed.js' {
  declare module.exports: $Exports<'vscode-languageserver-protocol/lib/protocol.workspaceFolders.proposed'>;
}
declare module 'vscode-languageserver-protocol/lib/utils/is.js' {
  declare module.exports: $Exports<'vscode-languageserver-protocol/lib/utils/is'>;
}
